export const appConfig = {
  JWT_SECRET: process.env.JWT_SECRET,
  BACKEND_URL: process.env.BACKEND_URL,
  CLOUDINARY_CLOUD_API_NAME: process.env.CLOUDINARY_CLOUD_API_NAME,
  CLOUDINARY_CLOUD_API_KEY: process.env.CLOUDINARY_CLOUD_API_KEY,
  CLOUDINARY_CLOUD_API_SECRET: process.env.CLOUDINARY_CLOUD_API_SECRET,
};
